name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    if: github.event.action != 'labeled'
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v3
      - 
        name: Download chart releaser
        run: |
          curl -sSLo hcr.tar.gz "https://github.com/pete911/hcr/releases/download/v0.0.5/hcr_0.0.5_linux_amd64.tar.gz"
          tar -xzf hcr.tar.gz
          rm -f hcr.tar.gz
      - 
        name: Package and release chart
        run: |
          ./hcr -token "${{ secrets.GITHUB_TOKEN }}"
